package db

import "context"

// HasAdminUser reports whether at least one user with role='admin' exists.
// This is a hand-written query (not generated by sqlc).
func (q *Queries) HasAdminUser(ctx context.Context) (bool, error) {
	var exists bool
	err := q.db.QueryRow(ctx, "SELECT EXISTS(SELECT 1 FROM users WHERE role = 'admin')").Scan(&exists)
	return exists, err
}
