// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ai_config.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteAIProviderConfig = `-- name: DeleteAIProviderConfig :exec
DELETE FROM ai_provider_configs WHERE id = $1
`

func (q *Queries) DeleteAIProviderConfig(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAIProviderConfig, id)
	return err
}

const getAIProviderConfig = `-- name: GetAIProviderConfig :one
SELECT id, provider_key, capability, encrypted_credentials, model, is_enabled, updated_at FROM ai_provider_configs
WHERE provider_key = $1 AND capability = $2
`

func (q *Queries) GetAIProviderConfig(ctx context.Context, providerKey string, capability string) (AiProviderConfig, error) {
	row := q.db.QueryRow(ctx, getAIProviderConfig, providerKey, capability)
	var i AiProviderConfig
	err := row.Scan(
		&i.ID,
		&i.ProviderKey,
		&i.Capability,
		&i.EncryptedCredentials,
		&i.Model,
		&i.IsEnabled,
		&i.UpdatedAt,
	)
	return i, err
}

const getAIProviderConfigByID = `-- name: GetAIProviderConfigByID :one
SELECT id, provider_key, capability, encrypted_credentials, model, is_enabled, updated_at FROM ai_provider_configs WHERE id = $1
`

func (q *Queries) GetAIProviderConfigByID(ctx context.Context, id pgtype.UUID) (AiProviderConfig, error) {
	row := q.db.QueryRow(ctx, getAIProviderConfigByID, id)
	var i AiProviderConfig
	err := row.Scan(
		&i.ID,
		&i.ProviderKey,
		&i.Capability,
		&i.EncryptedCredentials,
		&i.Model,
		&i.IsEnabled,
		&i.UpdatedAt,
	)
	return i, err
}

const listAIProviderConfigs = `-- name: ListAIProviderConfigs :many
SELECT id, provider_key, capability, encrypted_credentials, model, is_enabled, updated_at FROM ai_provider_configs
ORDER BY provider_key ASC, capability ASC
`

func (q *Queries) ListAIProviderConfigs(ctx context.Context) ([]AiProviderConfig, error) {
	rows, err := q.db.Query(ctx, listAIProviderConfigs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AiProviderConfig{}
	for rows.Next() {
		var i AiProviderConfig
		if err := rows.Scan(
			&i.ID,
			&i.ProviderKey,
			&i.Capability,
			&i.EncryptedCredentials,
			&i.Model,
			&i.IsEnabled,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnabledAIProviderConfigs = `-- name: ListEnabledAIProviderConfigs :many
SELECT id, provider_key, capability, encrypted_credentials, model, is_enabled, updated_at FROM ai_provider_configs
WHERE is_enabled = TRUE
ORDER BY provider_key ASC, capability ASC
`

func (q *Queries) ListEnabledAIProviderConfigs(ctx context.Context) ([]AiProviderConfig, error) {
	rows, err := q.db.Query(ctx, listEnabledAIProviderConfigs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AiProviderConfig{}
	for rows.Next() {
		var i AiProviderConfig
		if err := rows.Scan(
			&i.ID,
			&i.ProviderKey,
			&i.Capability,
			&i.EncryptedCredentials,
			&i.Model,
			&i.IsEnabled,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAIProviderConfig = `-- name: UpsertAIProviderConfig :one
INSERT INTO ai_provider_configs (provider_key, capability, encrypted_credentials, model, is_enabled, updated_at)
VALUES ($1, $2, $3, $4, $5, NOW())
ON CONFLICT (provider_key, capability) DO UPDATE
    SET encrypted_credentials = $3,
        model                 = $4,
        is_enabled            = $5,
        updated_at            = NOW()
RETURNING id, provider_key, capability, encrypted_credentials, model, is_enabled, updated_at
`

type UpsertAIProviderConfigParams struct {
	ProviderKey          string `db:"provider_key" json:"provider_key"`
	Capability           string `db:"capability" json:"capability"`
	EncryptedCredentials []byte `db:"encrypted_credentials" json:"encrypted_credentials"`
	Model                string `db:"model" json:"model"`
	IsEnabled            bool   `db:"is_enabled" json:"is_enabled"`
}

func (q *Queries) UpsertAIProviderConfig(ctx context.Context, arg UpsertAIProviderConfigParams) (AiProviderConfig, error) {
	row := q.db.QueryRow(ctx, upsertAIProviderConfig,
		arg.ProviderKey,
		arg.Capability,
		arg.EncryptedCredentials,
		arg.Model,
		arg.IsEnabled,
	)
	var i AiProviderConfig
	err := row.Scan(
		&i.ID,
		&i.ProviderKey,
		&i.Capability,
		&i.EncryptedCredentials,
		&i.Model,
		&i.IsEnabled,
		&i.UpdatedAt,
	)
	return i, err
}
