// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: content.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addTopicToContent = `-- name: AddTopicToContent :exec

INSERT INTO content_topics (content_id, topic_id)
VALUES ($1, $2)
ON CONFLICT (content_id, topic_id) DO NOTHING
`

// ───────────────────────── Contents ↔ Topics ─────────────────────────
func (q *Queries) AddTopicToContent(ctx context.Context, contentID pgtype.UUID, topicID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, addTopicToContent, contentID, topicID)
	return err
}

const addTopicToSubject = `-- name: AddTopicToSubject :exec

INSERT INTO subject_topics (subject_id, topic_id, position)
VALUES ($1, $2, $3)
ON CONFLICT (subject_id, topic_id) DO NOTHING
`

// ───────────────────────── Subjects ↔ Topics ─────────────────────────
func (q *Queries) AddTopicToSubject(ctx context.Context, subjectID pgtype.UUID, topicID pgtype.UUID, position int32) error {
	_, err := q.db.Exec(ctx, addTopicToSubject, subjectID, topicID, position)
	return err
}

const assignTeacherToSubject = `-- name: AssignTeacherToSubject :exec

INSERT INTO teachers_subjects (teacher_id, subject_id, assigned_by)
VALUES ($1, $2, $3)
ON CONFLICT (teacher_id, subject_id) DO NOTHING
`

// ───────────────────────── Teachers ↔ Subjects ─────────────────────────
func (q *Queries) AssignTeacherToSubject(ctx context.Context, teacherID pgtype.UUID, subjectID pgtype.UUID, assignedBy pgtype.UUID) error {
	_, err := q.db.Exec(ctx, assignTeacherToSubject, teacherID, subjectID, assignedBy)
	return err
}

const createBlock = `-- name: CreateBlock :one

INSERT INTO blocks (page_id, type, position, data)
VALUES ($1, $2, $3, $4)
RETURNING id, page_id, type, position, data, created_at, updated_at
`

// ───────────────────────── Blocks ─────────────────────────
func (q *Queries) CreateBlock(ctx context.Context, pageID pgtype.UUID, type_ string, position int32, data []byte) (Block, error) {
	row := q.db.QueryRow(ctx, createBlock,
		pageID,
		type_,
		position,
		data,
	)
	var i Block
	err := row.Scan(
		&i.ID,
		&i.PageID,
		&i.Type,
		&i.Position,
		&i.Data,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createContent = `-- name: CreateContent :one

INSERT INTO contents (subject_id, title, description, position, created_by)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, subject_id, title, description, position, created_by, created_at, updated_at
`

type CreateContentParams struct {
	SubjectID   pgtype.UUID `db:"subject_id" json:"subject_id"`
	Title       string      `db:"title" json:"title"`
	Description string      `db:"description" json:"description"`
	Position    int32       `db:"position" json:"position"`
	CreatedBy   pgtype.UUID `db:"created_by" json:"created_by"`
}

// ───────────────────────── Contents ─────────────────────────
func (q *Queries) CreateContent(ctx context.Context, arg CreateContentParams) (Content, error) {
	row := q.db.QueryRow(ctx, createContent,
		arg.SubjectID,
		arg.Title,
		arg.Description,
		arg.Position,
		arg.CreatedBy,
	)
	var i Content
	err := row.Scan(
		&i.ID,
		&i.SubjectID,
		&i.Title,
		&i.Description,
		&i.Position,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPage = `-- name: CreatePage :one

INSERT INTO pages (content_id, name, position, created_by)
VALUES ($1, $2, $3, $4)
RETURNING id, content_id, name, position, created_by, created_at, updated_at
`

// ───────────────────────── Pages ─────────────────────────
func (q *Queries) CreatePage(ctx context.Context, contentID pgtype.UUID, name string, position int32, createdBy pgtype.UUID) (Page, error) {
	row := q.db.QueryRow(ctx, createPage,
		contentID,
		name,
		position,
		createdBy,
	)
	var i Page
	err := row.Scan(
		&i.ID,
		&i.ContentID,
		&i.Name,
		&i.Position,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSubject = `-- name: CreateSubject :one

INSERT INTO subjects (name, description, cover_image_key, position, created_by)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, description, cover_image_key, position, created_by, created_at
`

type CreateSubjectParams struct {
	Name          string      `db:"name" json:"name"`
	Description   string      `db:"description" json:"description"`
	CoverImageKey *string     `db:"cover_image_key" json:"cover_image_key"`
	Position      int32       `db:"position" json:"position"`
	CreatedBy     pgtype.UUID `db:"created_by" json:"created_by"`
}

// ───────────────────────── Subjects ─────────────────────────
func (q *Queries) CreateSubject(ctx context.Context, arg CreateSubjectParams) (Subject, error) {
	row := q.db.QueryRow(ctx, createSubject,
		arg.Name,
		arg.Description,
		arg.CoverImageKey,
		arg.Position,
		arg.CreatedBy,
	)
	var i Subject
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CoverImageKey,
		&i.Position,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const createTopic = `-- name: CreateTopic :one

INSERT INTO topics (name, description, created_by)
VALUES ($1, $2, $3)
RETURNING id, name, description, created_by, created_at
`

// ───────────────────────── Topics ─────────────────────────
func (q *Queries) CreateTopic(ctx context.Context, name string, description string, createdBy pgtype.UUID) (Topic, error) {
	row := q.db.QueryRow(ctx, createTopic, name, description, createdBy)
	var i Topic
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const deleteBlock = `-- name: DeleteBlock :exec
DELETE FROM blocks WHERE id = $1
`

func (q *Queries) DeleteBlock(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteBlock, id)
	return err
}

const deleteBlocksByPage = `-- name: DeleteBlocksByPage :exec
DELETE FROM blocks WHERE page_id = $1
`

func (q *Queries) DeleteBlocksByPage(ctx context.Context, pageID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteBlocksByPage, pageID)
	return err
}

const deleteContent = `-- name: DeleteContent :exec
DELETE FROM contents WHERE id = $1
`

func (q *Queries) DeleteContent(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteContent, id)
	return err
}

const deletePage = `-- name: DeletePage :exec
DELETE FROM pages WHERE id = $1
`

func (q *Queries) DeletePage(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deletePage, id)
	return err
}

const deleteSubject = `-- name: DeleteSubject :exec
DELETE FROM subjects WHERE id = $1
`

func (q *Queries) DeleteSubject(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteSubject, id)
	return err
}

const deleteTeacherSubjectAssignments = `-- name: DeleteTeacherSubjectAssignments :exec
DELETE FROM teachers_subjects WHERE teacher_id = $1
`

func (q *Queries) DeleteTeacherSubjectAssignments(ctx context.Context, teacherID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteTeacherSubjectAssignments, teacherID)
	return err
}

const deleteTopic = `-- name: DeleteTopic :exec
DELETE FROM topics WHERE id = $1
`

func (q *Queries) DeleteTopic(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteTopic, id)
	return err
}

const getBlockByID = `-- name: GetBlockByID :one
SELECT id, page_id, type, position, data, created_at, updated_at FROM blocks WHERE id = $1
`

func (q *Queries) GetBlockByID(ctx context.Context, id pgtype.UUID) (Block, error) {
	row := q.db.QueryRow(ctx, getBlockByID, id)
	var i Block
	err := row.Scan(
		&i.ID,
		&i.PageID,
		&i.Type,
		&i.Position,
		&i.Data,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getContentByID = `-- name: GetContentByID :one
SELECT id, subject_id, title, description, position, created_by, created_at, updated_at FROM contents WHERE id = $1
`

func (q *Queries) GetContentByID(ctx context.Context, id pgtype.UUID) (Content, error) {
	row := q.db.QueryRow(ctx, getContentByID, id)
	var i Content
	err := row.Scan(
		&i.ID,
		&i.SubjectID,
		&i.Title,
		&i.Description,
		&i.Position,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPageByID = `-- name: GetPageByID :one
SELECT id, content_id, name, position, created_by, created_at, updated_at FROM pages WHERE id = $1
`

func (q *Queries) GetPageByID(ctx context.Context, id pgtype.UUID) (Page, error) {
	row := q.db.QueryRow(ctx, getPageByID, id)
	var i Page
	err := row.Scan(
		&i.ID,
		&i.ContentID,
		&i.Name,
		&i.Position,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSubjectByID = `-- name: GetSubjectByID :one
SELECT id, name, description, cover_image_key, position, created_by, created_at FROM subjects WHERE id = $1
`

func (q *Queries) GetSubjectByID(ctx context.Context, id pgtype.UUID) (Subject, error) {
	row := q.db.QueryRow(ctx, getSubjectByID, id)
	var i Subject
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CoverImageKey,
		&i.Position,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getTopicByID = `-- name: GetTopicByID :one
SELECT id, name, description, created_by, created_at FROM topics WHERE id = $1
`

func (q *Queries) GetTopicByID(ctx context.Context, id pgtype.UUID) (Topic, error) {
	row := q.db.QueryRow(ctx, getTopicByID, id)
	var i Topic
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listBlocksByPage = `-- name: ListBlocksByPage :many
SELECT id, page_id, type, position, data, created_at, updated_at FROM blocks WHERE page_id = $1 ORDER BY position ASC
`

func (q *Queries) ListBlocksByPage(ctx context.Context, pageID pgtype.UUID) ([]Block, error) {
	rows, err := q.db.Query(ctx, listBlocksByPage, pageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Block{}
	for rows.Next() {
		var i Block
		if err := rows.Scan(
			&i.ID,
			&i.PageID,
			&i.Type,
			&i.Position,
			&i.Data,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContentsBySubject = `-- name: ListContentsBySubject :many
SELECT id, subject_id, title, description, position, created_by, created_at, updated_at FROM contents WHERE subject_id = $1 ORDER BY position ASC
`

func (q *Queries) ListContentsBySubject(ctx context.Context, subjectID pgtype.UUID) ([]Content, error) {
	rows, err := q.db.Query(ctx, listContentsBySubject, subjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Content{}
	for rows.Next() {
		var i Content
		if err := rows.Scan(
			&i.ID,
			&i.SubjectID,
			&i.Title,
			&i.Description,
			&i.Position,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContentsByTopic = `-- name: ListContentsByTopic :many
SELECT c.id, c.subject_id, c.title, c.description, c.position, c.created_by, c.created_at, c.updated_at FROM contents c
JOIN content_topics ct ON ct.content_id = c.id
WHERE ct.topic_id = $1
ORDER BY c.position ASC
`

func (q *Queries) ListContentsByTopic(ctx context.Context, topicID pgtype.UUID) ([]Content, error) {
	rows, err := q.db.Query(ctx, listContentsByTopic, topicID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Content{}
	for rows.Next() {
		var i Content
		if err := rows.Scan(
			&i.ID,
			&i.SubjectID,
			&i.Title,
			&i.Description,
			&i.Position,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPagesByContent = `-- name: ListPagesByContent :many
SELECT id, content_id, name, position, created_by, created_at, updated_at FROM pages WHERE content_id = $1 ORDER BY position ASC
`

func (q *Queries) ListPagesByContent(ctx context.Context, contentID pgtype.UUID) ([]Page, error) {
	rows, err := q.db.Query(ctx, listPagesByContent, contentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Page{}
	for rows.Next() {
		var i Page
		if err := rows.Scan(
			&i.ID,
			&i.ContentID,
			&i.Name,
			&i.Position,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubjects = `-- name: ListSubjects :many
SELECT id, name, description, cover_image_key, position, created_by, created_at FROM subjects ORDER BY position ASC, created_at ASC
`

func (q *Queries) ListSubjects(ctx context.Context) ([]Subject, error) {
	rows, err := q.db.Query(ctx, listSubjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Subject{}
	for rows.Next() {
		var i Subject
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CoverImageKey,
			&i.Position,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubjectsByTeacher = `-- name: ListSubjectsByTeacher :many
SELECT s.id, s.name, s.description, s.cover_image_key, s.position, s.created_by, s.created_at FROM subjects s
JOIN teachers_subjects ts ON ts.subject_id = s.id
WHERE ts.teacher_id = $1
ORDER BY s.position ASC
`

func (q *Queries) ListSubjectsByTeacher(ctx context.Context, teacherID pgtype.UUID) ([]Subject, error) {
	rows, err := q.db.Query(ctx, listSubjectsByTeacher, teacherID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Subject{}
	for rows.Next() {
		var i Subject
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CoverImageKey,
			&i.Position,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeachersBySubject = `-- name: ListTeachersBySubject :many
SELECT u.id, u.username, u.email, u.password_hash, u.role, u.created_at FROM users u
JOIN teachers_subjects ts ON ts.teacher_id = u.id
WHERE ts.subject_id = $1
ORDER BY ts.assigned_at ASC
`

func (q *Queries) ListTeachersBySubject(ctx context.Context, subjectID pgtype.UUID) ([]User, error) {
	rows, err := q.db.Query(ctx, listTeachersBySubject, subjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.PasswordHash,
			&i.Role,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTopics = `-- name: ListTopics :many
SELECT id, name, description, created_by, created_at FROM topics ORDER BY name ASC
`

func (q *Queries) ListTopics(ctx context.Context) ([]Topic, error) {
	rows, err := q.db.Query(ctx, listTopics)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Topic{}
	for rows.Next() {
		var i Topic
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTopicsByContent = `-- name: ListTopicsByContent :many
SELECT t.id, t.name, t.description, t.created_by, t.created_at FROM topics t
JOIN content_topics ct ON ct.topic_id = t.id
WHERE ct.content_id = $1
ORDER BY t.name ASC
`

func (q *Queries) ListTopicsByContent(ctx context.Context, contentID pgtype.UUID) ([]Topic, error) {
	rows, err := q.db.Query(ctx, listTopicsByContent, contentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Topic{}
	for rows.Next() {
		var i Topic
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTopicsBySubject = `-- name: ListTopicsBySubject :many
SELECT t.id, t.name, t.description, t.created_by, t.created_at FROM topics t
JOIN subject_topics st ON st.topic_id = t.id
WHERE st.subject_id = $1
ORDER BY st.position ASC
`

func (q *Queries) ListTopicsBySubject(ctx context.Context, subjectID pgtype.UUID) ([]Topic, error) {
	rows, err := q.db.Query(ctx, listTopicsBySubject, subjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Topic{}
	for rows.Next() {
		var i Topic
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeTopicFromContent = `-- name: RemoveTopicFromContent :exec
DELETE FROM content_topics WHERE content_id = $1 AND topic_id = $2
`

func (q *Queries) RemoveTopicFromContent(ctx context.Context, contentID pgtype.UUID, topicID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, removeTopicFromContent, contentID, topicID)
	return err
}

const removeTopicFromSubject = `-- name: RemoveTopicFromSubject :exec
DELETE FROM subject_topics WHERE subject_id = $1 AND topic_id = $2
`

func (q *Queries) RemoveTopicFromSubject(ctx context.Context, subjectID pgtype.UUID, topicID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, removeTopicFromSubject, subjectID, topicID)
	return err
}

const replaceContentTopics = `-- name: ReplaceContentTopics :exec
DELETE FROM content_topics WHERE content_id = $1
`

func (q *Queries) ReplaceContentTopics(ctx context.Context, contentID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, replaceContentTopics, contentID)
	return err
}

const unassignTeacherFromSubject = `-- name: UnassignTeacherFromSubject :exec
DELETE FROM teachers_subjects WHERE teacher_id = $1 AND subject_id = $2
`

func (q *Queries) UnassignTeacherFromSubject(ctx context.Context, teacherID pgtype.UUID, subjectID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, unassignTeacherFromSubject, teacherID, subjectID)
	return err
}

const updateBlock = `-- name: UpdateBlock :one
UPDATE blocks
SET type = $2, position = $3, data = $4, updated_at = NOW()
WHERE id = $1
RETURNING id, page_id, type, position, data, created_at, updated_at
`

func (q *Queries) UpdateBlock(ctx context.Context, iD pgtype.UUID, type_ string, position int32, data []byte) (Block, error) {
	row := q.db.QueryRow(ctx, updateBlock,
		iD,
		type_,
		position,
		data,
	)
	var i Block
	err := row.Scan(
		&i.ID,
		&i.PageID,
		&i.Type,
		&i.Position,
		&i.Data,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateContent = `-- name: UpdateContent :one
UPDATE contents
SET title = $2, description = $3, position = $4, updated_at = NOW()
WHERE id = $1
RETURNING id, subject_id, title, description, position, created_by, created_at, updated_at
`

func (q *Queries) UpdateContent(ctx context.Context, iD pgtype.UUID, title string, description string, position int32) (Content, error) {
	row := q.db.QueryRow(ctx, updateContent,
		iD,
		title,
		description,
		position,
	)
	var i Content
	err := row.Scan(
		&i.ID,
		&i.SubjectID,
		&i.Title,
		&i.Description,
		&i.Position,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePage = `-- name: UpdatePage :one
UPDATE pages
SET name = $2, position = $3, updated_at = NOW()
WHERE id = $1
RETURNING id, content_id, name, position, created_by, created_at, updated_at
`

func (q *Queries) UpdatePage(ctx context.Context, iD pgtype.UUID, name string, position int32) (Page, error) {
	row := q.db.QueryRow(ctx, updatePage, iD, name, position)
	var i Page
	err := row.Scan(
		&i.ID,
		&i.ContentID,
		&i.Name,
		&i.Position,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSubject = `-- name: UpdateSubject :one
UPDATE subjects
SET name = $2, description = $3, cover_image_key = $4, position = $5
WHERE id = $1
RETURNING id, name, description, cover_image_key, position, created_by, created_at
`

type UpdateSubjectParams struct {
	ID            pgtype.UUID `db:"id" json:"id"`
	Name          string      `db:"name" json:"name"`
	Description   string      `db:"description" json:"description"`
	CoverImageKey *string     `db:"cover_image_key" json:"cover_image_key"`
	Position      int32       `db:"position" json:"position"`
}

func (q *Queries) UpdateSubject(ctx context.Context, arg UpdateSubjectParams) (Subject, error) {
	row := q.db.QueryRow(ctx, updateSubject,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.CoverImageKey,
		arg.Position,
	)
	var i Subject
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CoverImageKey,
		&i.Position,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const updateTopic = `-- name: UpdateTopic :one
UPDATE topics SET name = $2, description = $3 WHERE id = $1 RETURNING id, name, description, created_by, created_at
`

func (q *Queries) UpdateTopic(ctx context.Context, iD pgtype.UUID, name string, description string) (Topic, error) {
	row := q.db.QueryRow(ctx, updateTopic, iD, name, description)
	var i Topic
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}
