// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AiProviderConfig struct {
	ID                   pgtype.UUID        `db:"id" json:"id"`
	ProviderKey          string             `db:"provider_key" json:"provider_key"`
	Capability           string             `db:"capability" json:"capability"`
	EncryptedCredentials []byte             `db:"encrypted_credentials" json:"encrypted_credentials"`
	Model                string             `db:"model" json:"model"`
	IsEnabled            bool               `db:"is_enabled" json:"is_enabled"`
	UpdatedAt            pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type Assessment struct {
	ID               pgtype.UUID        `db:"id" json:"id"`
	Title            string             `db:"title" json:"title"`
	Description      string             `db:"description" json:"description"`
	SubjectID        pgtype.UUID        `db:"subject_id" json:"subject_id"`
	TimeLimitSeconds *int32             `db:"time_limit_seconds" json:"time_limit_seconds"`
	PassingScore     *int32             `db:"passing_score" json:"passing_score"`
	CreatedBy        pgtype.UUID        `db:"created_by" json:"created_by"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type AssessmentQuestion struct {
	AssessmentID pgtype.UUID `db:"assessment_id" json:"assessment_id"`
	QuestionID   pgtype.UUID `db:"question_id" json:"question_id"`
	Position     int32       `db:"position" json:"position"`
}

type AssessmentTopic struct {
	AssessmentID pgtype.UUID `db:"assessment_id" json:"assessment_id"`
	TopicID      pgtype.UUID `db:"topic_id" json:"topic_id"`
}

type Block struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	PageID    pgtype.UUID        `db:"page_id" json:"page_id"`
	Type      string             `db:"type" json:"type"`
	Position  int32              `db:"position" json:"position"`
	Data      []byte             `db:"data" json:"data"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type Content struct {
	ID          pgtype.UUID        `db:"id" json:"id"`
	SubjectID   pgtype.UUID        `db:"subject_id" json:"subject_id"`
	Title       string             `db:"title" json:"title"`
	Description string             `db:"description" json:"description"`
	Position    int32              `db:"position" json:"position"`
	CreatedBy   pgtype.UUID        `db:"created_by" json:"created_by"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type ContentTopic struct {
	ContentID pgtype.UUID `db:"content_id" json:"content_id"`
	TopicID   pgtype.UUID `db:"topic_id" json:"topic_id"`
}

type Invitation struct {
	ID         pgtype.UUID        `db:"id" json:"id"`
	Email      string             `db:"email" json:"email"`
	Role       string             `db:"role" json:"role"`
	TokenHash  string             `db:"token_hash" json:"token_hash"`
	InvitedBy  pgtype.UUID        `db:"invited_by" json:"invited_by"`
	ExpiresAt  pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	AcceptedAt pgtype.Timestamptz `db:"accepted_at" json:"accepted_at"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type LoginAttempt struct {
	ID                  pgtype.UUID        `db:"id" json:"id"`
	Username            string             `db:"username" json:"username"`
	Ip                  string             `db:"ip" json:"ip"`
	PasswordFingerprint *string            `db:"password_fingerprint" json:"password_fingerprint"`
	AttemptedAt         pgtype.Timestamptz `db:"attempted_at" json:"attempted_at"`
	Success             bool               `db:"success" json:"success"`
}

type LoginRateLimit struct {
	ScopeType string             `db:"scope_type" json:"scope_type"`
	ScopeKey  string             `db:"scope_key" json:"scope_key"`
	Tokens    int32              `db:"tokens" json:"tokens"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type Page struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	ContentID pgtype.UUID        `db:"content_id" json:"content_id"`
	Name      string             `db:"name" json:"name"`
	Position  int32              `db:"position" json:"position"`
	CreatedBy pgtype.UUID        `db:"created_by" json:"created_by"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type Passkey struct {
	ID           pgtype.UUID        `db:"id" json:"id"`
	UserID       pgtype.UUID        `db:"user_id" json:"user_id"`
	CredentialID []byte             `db:"credential_id" json:"credential_id"`
	PublicKey    []byte             `db:"public_key" json:"public_key"`
	SignCount    int64              `db:"sign_count" json:"sign_count"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type Question struct {
	ID         pgtype.UUID        `db:"id" json:"id"`
	SubjectID  pgtype.UUID        `db:"subject_id" json:"subject_id"`
	StemType   string             `db:"stem_type" json:"stem_type"`
	StemData   []byte             `db:"stem_data" json:"stem_data"`
	Type       string             `db:"type" json:"type"`
	AnswerData []byte             `db:"answer_data" json:"answer_data"`
	Tags       []string           `db:"tags" json:"tags"`
	CreatedBy  pgtype.UUID        `db:"created_by" json:"created_by"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type QuestionTopic struct {
	QuestionID pgtype.UUID `db:"question_id" json:"question_id"`
	TopicID    pgtype.UUID `db:"topic_id" json:"topic_id"`
}

type Session struct {
	ID         pgtype.UUID        `db:"id" json:"id"`
	UserID     pgtype.UUID        `db:"user_id" json:"user_id"`
	TokenHash  string             `db:"token_hash" json:"token_hash"`
	ExpiresAt  pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	LastSeenAt pgtype.Timestamptz `db:"last_seen_at" json:"last_seen_at"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type Subject struct {
	ID            pgtype.UUID        `db:"id" json:"id"`
	Name          string             `db:"name" json:"name"`
	Description   string             `db:"description" json:"description"`
	CoverImageKey *string            `db:"cover_image_key" json:"cover_image_key"`
	Position      int32              `db:"position" json:"position"`
	CreatedBy     pgtype.UUID        `db:"created_by" json:"created_by"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type SubjectTopic struct {
	SubjectID pgtype.UUID `db:"subject_id" json:"subject_id"`
	TopicID   pgtype.UUID `db:"topic_id" json:"topic_id"`
	Position  int32       `db:"position" json:"position"`
}

type TeachersSubject struct {
	TeacherID  pgtype.UUID        `db:"teacher_id" json:"teacher_id"`
	SubjectID  pgtype.UUID        `db:"subject_id" json:"subject_id"`
	AssignedBy pgtype.UUID        `db:"assigned_by" json:"assigned_by"`
	AssignedAt pgtype.Timestamptz `db:"assigned_at" json:"assigned_at"`
}

type Topic struct {
	ID          pgtype.UUID        `db:"id" json:"id"`
	Name        string             `db:"name" json:"name"`
	Description string             `db:"description" json:"description"`
	CreatedBy   pgtype.UUID        `db:"created_by" json:"created_by"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type User struct {
	ID           pgtype.UUID        `db:"id" json:"id"`
	Username     string             `db:"username" json:"username"`
	Email        string             `db:"email" json:"email"`
	PasswordHash string             `db:"password_hash" json:"password_hash"`
	Role         string             `db:"role" json:"role"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
}
