// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AcceptInvitation(ctx context.Context, id pgtype.UUID) (Invitation, error)
	// ───────────────────────── Assessments ↔ Questions ─────────────────────────
	AddQuestionToAssessment(ctx context.Context, assessmentID pgtype.UUID, questionID pgtype.UUID, position int32) error
	// ───────────────────────── Assessments ↔ Topics ─────────────────────────
	AddTopicToAssessment(ctx context.Context, assessmentID pgtype.UUID, topicID pgtype.UUID) error
	// ───────────────────────── Contents ↔ Topics ─────────────────────────
	AddTopicToContent(ctx context.Context, contentID pgtype.UUID, topicID pgtype.UUID) error
	// ───────────────────────── Questions ↔ Topics ─────────────────────────
	AddTopicToQuestion(ctx context.Context, questionID pgtype.UUID, topicID pgtype.UUID) error
	// ───────────────────────── Subjects ↔ Topics ─────────────────────────
	AddTopicToSubject(ctx context.Context, subjectID pgtype.UUID, topicID pgtype.UUID, position int32) error
	// ───────────────────────── Teachers ↔ Subjects ─────────────────────────
	AssignTeacherToSubject(ctx context.Context, teacherID pgtype.UUID, subjectID pgtype.UUID, assignedBy pgtype.UUID) error
	// ───────────────────────── Assessments ─────────────────────────
	CreateAssessment(ctx context.Context, arg CreateAssessmentParams) (Assessment, error)
	// ───────────────────────── Blocks ─────────────────────────
	CreateBlock(ctx context.Context, pageID pgtype.UUID, type_ string, position int32, data []byte) (Block, error)
	// ───────────────────────── Contents ─────────────────────────
	CreateContent(ctx context.Context, arg CreateContentParams) (Content, error)
	CreateInvitation(ctx context.Context, arg CreateInvitationParams) (Invitation, error)
	// ───────────────────────── Login Attempts ─────────────────────────
	CreateLoginAttempt(ctx context.Context, username string, ip string, passwordFingerprint *string, success bool) (LoginAttempt, error)
	// ───────────────────────── Pages ─────────────────────────
	CreatePage(ctx context.Context, contentID pgtype.UUID, name string, position int32, createdBy pgtype.UUID) (Page, error)
	// ───────────────────────── Passkeys ─────────────────────────
	CreatePasskey(ctx context.Context, userID pgtype.UUID, credentialID []byte, publicKey []byte, signCount int64) (Passkey, error)
	// ───────────────────────── Questions ─────────────────────────
	CreateQuestion(ctx context.Context, arg CreateQuestionParams) (Question, error)
	// ───────────────────────── Sessions ─────────────────────────
	CreateSession(ctx context.Context, userID pgtype.UUID, tokenHash string, expiresAt pgtype.Timestamptz) (Session, error)
	// ───────────────────────── Subjects ─────────────────────────
	CreateSubject(ctx context.Context, arg CreateSubjectParams) (Subject, error)
	// ───────────────────────── Topics ─────────────────────────
	CreateTopic(ctx context.Context, name string, description string, createdBy pgtype.UUID) (Topic, error)
	CreateUser(ctx context.Context, username string, email string, passwordHash string, role string) (User, error)
	DeleteAIProviderConfig(ctx context.Context, id pgtype.UUID) error
	DeleteAssessment(ctx context.Context, id pgtype.UUID) error
	DeleteBlock(ctx context.Context, id pgtype.UUID) error
	DeleteBlocksByPage(ctx context.Context, pageID pgtype.UUID) error
	DeleteContent(ctx context.Context, id pgtype.UUID) error
	DeleteExpiredInvitations(ctx context.Context) error
	DeleteExpiredSessions(ctx context.Context) error
	DeleteInvitation(ctx context.Context, id pgtype.UUID) error
	DeleteLoginRateLimit(ctx context.Context, scopeType string, scopeKey string) error
	DeletePage(ctx context.Context, id pgtype.UUID) error
	DeletePasskey(ctx context.Context, id pgtype.UUID) error
	DeleteQuestion(ctx context.Context, id pgtype.UUID) error
	DeleteSession(ctx context.Context, id pgtype.UUID) error
	DeleteSubject(ctx context.Context, id pgtype.UUID) error
	DeleteTeacherSubjectAssignments(ctx context.Context, teacherID pgtype.UUID) error
	DeleteTopic(ctx context.Context, id pgtype.UUID) error
	DeleteUser(ctx context.Context, id pgtype.UUID) error
	GetAIProviderConfig(ctx context.Context, providerKey string, capability string) (AiProviderConfig, error)
	GetAIProviderConfigByID(ctx context.Context, id pgtype.UUID) (AiProviderConfig, error)
	GetAssessmentByID(ctx context.Context, id pgtype.UUID) (Assessment, error)
	GetBlockByID(ctx context.Context, id pgtype.UUID) (Block, error)
	GetContentByID(ctx context.Context, id pgtype.UUID) (Content, error)
	GetInvitationByID(ctx context.Context, id pgtype.UUID) (Invitation, error)
	GetInvitationByTokenHash(ctx context.Context, tokenHash string) (Invitation, error)
	// ───────────────────────── Login Rate Limits ─────────────────────────
	GetLoginRateLimit(ctx context.Context, scopeType string, scopeKey string) (LoginRateLimit, error)
	GetPageByID(ctx context.Context, id pgtype.UUID) (Page, error)
	GetPasskeyByCredentialID(ctx context.Context, credentialID []byte) (Passkey, error)
	GetQuestionByID(ctx context.Context, id pgtype.UUID) (Question, error)
	GetSessionByTokenHash(ctx context.Context, tokenHash string) (Session, error)
	GetSubjectByID(ctx context.Context, id pgtype.UUID) (Subject, error)
	GetTopicByID(ctx context.Context, id pgtype.UUID) (Topic, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	// ───────────────────────── Users ─────────────────────────
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	ListAIProviderConfigs(ctx context.Context) ([]AiProviderConfig, error)
	ListAIProviderConfigsByProvider(ctx context.Context, providerKey string) ([]AiProviderConfig, error)
	ListAssessmentsBySubject(ctx context.Context, subjectID pgtype.UUID) ([]Assessment, error)
	ListBlocksByPage(ctx context.Context, pageID pgtype.UUID) ([]Block, error)
	ListContentsBySubject(ctx context.Context, subjectID pgtype.UUID) ([]Content, error)
	ListContentsByTopic(ctx context.Context, topicID pgtype.UUID) ([]Content, error)
	ListEnabledAIProviderConfigs(ctx context.Context) ([]AiProviderConfig, error)
	ListPagesByContent(ctx context.Context, contentID pgtype.UUID) ([]Page, error)
	ListPasskeysByUserID(ctx context.Context, userID pgtype.UUID) ([]Passkey, error)
	ListPendingInvitations(ctx context.Context) ([]Invitation, error)
	ListQuestionsByAssessment(ctx context.Context, assessmentID pgtype.UUID) ([]Question, error)
	ListQuestionsBySubject(ctx context.Context, subjectID pgtype.UUID) ([]Question, error)
	ListQuestionsByTopic(ctx context.Context, topicID pgtype.UUID) ([]Question, error)
	ListRecentLoginAttemptsByIP(ctx context.Context, ip string) ([]LoginAttempt, error)
	ListRecentLoginAttemptsByUsername(ctx context.Context, username string) ([]LoginAttempt, error)
	ListSubjects(ctx context.Context) ([]Subject, error)
	ListSubjectsByTeacher(ctx context.Context, teacherID pgtype.UUID) ([]Subject, error)
	ListTeachersBySubject(ctx context.Context, subjectID pgtype.UUID) ([]User, error)
	ListTopics(ctx context.Context) ([]Topic, error)
	ListTopicsByAssessment(ctx context.Context, assessmentID pgtype.UUID) ([]Topic, error)
	ListTopicsByContent(ctx context.Context, contentID pgtype.UUID) ([]Topic, error)
	ListTopicsByQuestion(ctx context.Context, questionID pgtype.UUID) ([]Topic, error)
	ListTopicsBySubject(ctx context.Context, subjectID pgtype.UUID) ([]Topic, error)
	ListUsers(ctx context.Context) ([]User, error)
	ListUsersByRole(ctx context.Context, role string) ([]User, error)
	RemoveQuestionFromAssessment(ctx context.Context, assessmentID pgtype.UUID, questionID pgtype.UUID) error
	RemoveTopicFromAssessment(ctx context.Context, assessmentID pgtype.UUID, topicID pgtype.UUID) error
	RemoveTopicFromContent(ctx context.Context, contentID pgtype.UUID, topicID pgtype.UUID) error
	RemoveTopicFromQuestion(ctx context.Context, questionID pgtype.UUID, topicID pgtype.UUID) error
	RemoveTopicFromSubject(ctx context.Context, subjectID pgtype.UUID, topicID pgtype.UUID) error
	ReplaceContentTopics(ctx context.Context, contentID pgtype.UUID) error
	UnassignTeacherFromSubject(ctx context.Context, teacherID pgtype.UUID, subjectID pgtype.UUID) error
	UpdateAssessment(ctx context.Context, arg UpdateAssessmentParams) (Assessment, error)
	UpdateAssessmentQuestionPosition(ctx context.Context, assessmentID pgtype.UUID, questionID pgtype.UUID, position int32) error
	UpdateBlock(ctx context.Context, iD pgtype.UUID, type_ string, position int32, data []byte) (Block, error)
	UpdateContent(ctx context.Context, iD pgtype.UUID, title string, description string, position int32) (Content, error)
	UpdatePage(ctx context.Context, iD pgtype.UUID, name string, position int32) (Page, error)
	UpdatePasskeySignCount(ctx context.Context, iD pgtype.UUID, signCount int64) (Passkey, error)
	UpdateQuestion(ctx context.Context, arg UpdateQuestionParams) (Question, error)
	UpdateSessionLastSeen(ctx context.Context, id pgtype.UUID) error
	UpdateSubject(ctx context.Context, arg UpdateSubjectParams) (Subject, error)
	UpdateTopic(ctx context.Context, iD pgtype.UUID, name string, description string) (Topic, error)
	UpdateUserPasswordHash(ctx context.Context, iD pgtype.UUID, passwordHash string) (User, error)
	UpdateUserRole(ctx context.Context, iD pgtype.UUID, role string) (User, error)
	UpsertAIProviderConfig(ctx context.Context, arg UpsertAIProviderConfigParams) (AiProviderConfig, error)
	UpsertLoginRateLimit(ctx context.Context, scopeType string, scopeKey string, tokens int32) (LoginRateLimit, error)
}

var _ Querier = (*Queries)(nil)
