// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: questions_assessments.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addQuestionToAssessment = `-- name: AddQuestionToAssessment :exec

INSERT INTO assessment_questions (assessment_id, question_id, position)
VALUES ($1, $2, $3)
ON CONFLICT (assessment_id, question_id) DO NOTHING
`

// ───────────────────────── Assessments ↔ Questions ─────────────────────────
func (q *Queries) AddQuestionToAssessment(ctx context.Context, assessmentID pgtype.UUID, questionID pgtype.UUID, position int32) error {
	_, err := q.db.Exec(ctx, addQuestionToAssessment, assessmentID, questionID, position)
	return err
}

const addTopicToAssessment = `-- name: AddTopicToAssessment :exec

INSERT INTO assessment_topics (assessment_id, topic_id)
VALUES ($1, $2)
ON CONFLICT (assessment_id, topic_id) DO NOTHING
`

// ───────────────────────── Assessments ↔ Topics ─────────────────────────
func (q *Queries) AddTopicToAssessment(ctx context.Context, assessmentID pgtype.UUID, topicID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, addTopicToAssessment, assessmentID, topicID)
	return err
}

const addTopicToQuestion = `-- name: AddTopicToQuestion :exec

INSERT INTO question_topics (question_id, topic_id)
VALUES ($1, $2)
ON CONFLICT (question_id, topic_id) DO NOTHING
`

// ───────────────────────── Questions ↔ Topics ─────────────────────────
func (q *Queries) AddTopicToQuestion(ctx context.Context, questionID pgtype.UUID, topicID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, addTopicToQuestion, questionID, topicID)
	return err
}

const createAssessment = `-- name: CreateAssessment :one

INSERT INTO assessments (title, description, subject_id, time_limit_seconds, passing_score, created_by)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, title, description, subject_id, time_limit_seconds, passing_score, created_by, created_at
`

type CreateAssessmentParams struct {
	Title            string      `db:"title" json:"title"`
	Description      string      `db:"description" json:"description"`
	SubjectID        pgtype.UUID `db:"subject_id" json:"subject_id"`
	TimeLimitSeconds *int32      `db:"time_limit_seconds" json:"time_limit_seconds"`
	PassingScore     *int32      `db:"passing_score" json:"passing_score"`
	CreatedBy        pgtype.UUID `db:"created_by" json:"created_by"`
}

// ───────────────────────── Assessments ─────────────────────────
func (q *Queries) CreateAssessment(ctx context.Context, arg CreateAssessmentParams) (Assessment, error) {
	row := q.db.QueryRow(ctx, createAssessment,
		arg.Title,
		arg.Description,
		arg.SubjectID,
		arg.TimeLimitSeconds,
		arg.PassingScore,
		arg.CreatedBy,
	)
	var i Assessment
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.SubjectID,
		&i.TimeLimitSeconds,
		&i.PassingScore,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const createQuestion = `-- name: CreateQuestion :one

INSERT INTO questions (subject_id, stem_type, stem_data, type, answer_data, tags, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, subject_id, stem_type, stem_data, type, answer_data, tags, created_by, created_at
`

type CreateQuestionParams struct {
	SubjectID  pgtype.UUID `db:"subject_id" json:"subject_id"`
	StemType   string      `db:"stem_type" json:"stem_type"`
	StemData   []byte      `db:"stem_data" json:"stem_data"`
	Type       string      `db:"type" json:"type"`
	AnswerData []byte      `db:"answer_data" json:"answer_data"`
	Tags       []string    `db:"tags" json:"tags"`
	CreatedBy  pgtype.UUID `db:"created_by" json:"created_by"`
}

// ───────────────────────── Questions ─────────────────────────
func (q *Queries) CreateQuestion(ctx context.Context, arg CreateQuestionParams) (Question, error) {
	row := q.db.QueryRow(ctx, createQuestion,
		arg.SubjectID,
		arg.StemType,
		arg.StemData,
		arg.Type,
		arg.AnswerData,
		arg.Tags,
		arg.CreatedBy,
	)
	var i Question
	err := row.Scan(
		&i.ID,
		&i.SubjectID,
		&i.StemType,
		&i.StemData,
		&i.Type,
		&i.AnswerData,
		&i.Tags,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAssessment = `-- name: DeleteAssessment :exec
DELETE FROM assessments WHERE id = $1
`

func (q *Queries) DeleteAssessment(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAssessment, id)
	return err
}

const deleteQuestion = `-- name: DeleteQuestion :exec
DELETE FROM questions WHERE id = $1
`

func (q *Queries) DeleteQuestion(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteQuestion, id)
	return err
}

const getAssessmentByID = `-- name: GetAssessmentByID :one
SELECT id, title, description, subject_id, time_limit_seconds, passing_score, created_by, created_at FROM assessments WHERE id = $1
`

func (q *Queries) GetAssessmentByID(ctx context.Context, id pgtype.UUID) (Assessment, error) {
	row := q.db.QueryRow(ctx, getAssessmentByID, id)
	var i Assessment
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.SubjectID,
		&i.TimeLimitSeconds,
		&i.PassingScore,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getQuestionByID = `-- name: GetQuestionByID :one
SELECT id, subject_id, stem_type, stem_data, type, answer_data, tags, created_by, created_at FROM questions WHERE id = $1
`

func (q *Queries) GetQuestionByID(ctx context.Context, id pgtype.UUID) (Question, error) {
	row := q.db.QueryRow(ctx, getQuestionByID, id)
	var i Question
	err := row.Scan(
		&i.ID,
		&i.SubjectID,
		&i.StemType,
		&i.StemData,
		&i.Type,
		&i.AnswerData,
		&i.Tags,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listAssessmentsBySubject = `-- name: ListAssessmentsBySubject :many
SELECT id, title, description, subject_id, time_limit_seconds, passing_score, created_by, created_at FROM assessments WHERE subject_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListAssessmentsBySubject(ctx context.Context, subjectID pgtype.UUID) ([]Assessment, error) {
	rows, err := q.db.Query(ctx, listAssessmentsBySubject, subjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Assessment{}
	for rows.Next() {
		var i Assessment
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.SubjectID,
			&i.TimeLimitSeconds,
			&i.PassingScore,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQuestionsByAssessment = `-- name: ListQuestionsByAssessment :many
SELECT q.id, q.subject_id, q.stem_type, q.stem_data, q.type, q.answer_data, q.tags, q.created_by, q.created_at FROM questions q
JOIN assessment_questions aq ON aq.question_id = q.id
WHERE aq.assessment_id = $1
ORDER BY aq.position ASC
`

func (q *Queries) ListQuestionsByAssessment(ctx context.Context, assessmentID pgtype.UUID) ([]Question, error) {
	rows, err := q.db.Query(ctx, listQuestionsByAssessment, assessmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Question{}
	for rows.Next() {
		var i Question
		if err := rows.Scan(
			&i.ID,
			&i.SubjectID,
			&i.StemType,
			&i.StemData,
			&i.Type,
			&i.AnswerData,
			&i.Tags,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQuestionsBySubject = `-- name: ListQuestionsBySubject :many
SELECT id, subject_id, stem_type, stem_data, type, answer_data, tags, created_by, created_at FROM questions WHERE subject_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListQuestionsBySubject(ctx context.Context, subjectID pgtype.UUID) ([]Question, error) {
	rows, err := q.db.Query(ctx, listQuestionsBySubject, subjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Question{}
	for rows.Next() {
		var i Question
		if err := rows.Scan(
			&i.ID,
			&i.SubjectID,
			&i.StemType,
			&i.StemData,
			&i.Type,
			&i.AnswerData,
			&i.Tags,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQuestionsByTopic = `-- name: ListQuestionsByTopic :many
SELECT q.id, q.subject_id, q.stem_type, q.stem_data, q.type, q.answer_data, q.tags, q.created_by, q.created_at FROM questions q
JOIN question_topics qt ON qt.question_id = q.id
WHERE qt.topic_id = $1
ORDER BY q.created_at DESC
`

func (q *Queries) ListQuestionsByTopic(ctx context.Context, topicID pgtype.UUID) ([]Question, error) {
	rows, err := q.db.Query(ctx, listQuestionsByTopic, topicID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Question{}
	for rows.Next() {
		var i Question
		if err := rows.Scan(
			&i.ID,
			&i.SubjectID,
			&i.StemType,
			&i.StemData,
			&i.Type,
			&i.AnswerData,
			&i.Tags,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTopicsByAssessment = `-- name: ListTopicsByAssessment :many
SELECT t.id, t.name, t.description, t.created_by, t.created_at FROM topics t
JOIN assessment_topics ato ON ato.topic_id = t.id
WHERE ato.assessment_id = $1
ORDER BY t.name ASC
`

func (q *Queries) ListTopicsByAssessment(ctx context.Context, assessmentID pgtype.UUID) ([]Topic, error) {
	rows, err := q.db.Query(ctx, listTopicsByAssessment, assessmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Topic{}
	for rows.Next() {
		var i Topic
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTopicsByQuestion = `-- name: ListTopicsByQuestion :many
SELECT t.id, t.name, t.description, t.created_by, t.created_at FROM topics t
JOIN question_topics qt ON qt.topic_id = t.id
WHERE qt.question_id = $1
ORDER BY t.name ASC
`

func (q *Queries) ListTopicsByQuestion(ctx context.Context, questionID pgtype.UUID) ([]Topic, error) {
	rows, err := q.db.Query(ctx, listTopicsByQuestion, questionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Topic{}
	for rows.Next() {
		var i Topic
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeQuestionFromAssessment = `-- name: RemoveQuestionFromAssessment :exec
DELETE FROM assessment_questions WHERE assessment_id = $1 AND question_id = $2
`

func (q *Queries) RemoveQuestionFromAssessment(ctx context.Context, assessmentID pgtype.UUID, questionID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, removeQuestionFromAssessment, assessmentID, questionID)
	return err
}

const removeTopicFromAssessment = `-- name: RemoveTopicFromAssessment :exec
DELETE FROM assessment_topics WHERE assessment_id = $1 AND topic_id = $2
`

func (q *Queries) RemoveTopicFromAssessment(ctx context.Context, assessmentID pgtype.UUID, topicID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, removeTopicFromAssessment, assessmentID, topicID)
	return err
}

const removeTopicFromQuestion = `-- name: RemoveTopicFromQuestion :exec
DELETE FROM question_topics WHERE question_id = $1 AND topic_id = $2
`

func (q *Queries) RemoveTopicFromQuestion(ctx context.Context, questionID pgtype.UUID, topicID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, removeTopicFromQuestion, questionID, topicID)
	return err
}

const updateAssessment = `-- name: UpdateAssessment :one
UPDATE assessments
SET title = $2, description = $3, time_limit_seconds = $4, passing_score = $5
WHERE id = $1
RETURNING id, title, description, subject_id, time_limit_seconds, passing_score, created_by, created_at
`

type UpdateAssessmentParams struct {
	ID               pgtype.UUID `db:"id" json:"id"`
	Title            string      `db:"title" json:"title"`
	Description      string      `db:"description" json:"description"`
	TimeLimitSeconds *int32      `db:"time_limit_seconds" json:"time_limit_seconds"`
	PassingScore     *int32      `db:"passing_score" json:"passing_score"`
}

func (q *Queries) UpdateAssessment(ctx context.Context, arg UpdateAssessmentParams) (Assessment, error) {
	row := q.db.QueryRow(ctx, updateAssessment,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.TimeLimitSeconds,
		arg.PassingScore,
	)
	var i Assessment
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.SubjectID,
		&i.TimeLimitSeconds,
		&i.PassingScore,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const updateAssessmentQuestionPosition = `-- name: UpdateAssessmentQuestionPosition :exec
UPDATE assessment_questions
SET position = $3
WHERE assessment_id = $1 AND question_id = $2
`

func (q *Queries) UpdateAssessmentQuestionPosition(ctx context.Context, assessmentID pgtype.UUID, questionID pgtype.UUID, position int32) error {
	_, err := q.db.Exec(ctx, updateAssessmentQuestionPosition, assessmentID, questionID, position)
	return err
}

const updateQuestion = `-- name: UpdateQuestion :one
UPDATE questions
SET stem_type = $2, stem_data = $3, type = $4, answer_data = $5, tags = $6
WHERE id = $1
RETURNING id, subject_id, stem_type, stem_data, type, answer_data, tags, created_by, created_at
`

type UpdateQuestionParams struct {
	ID         pgtype.UUID `db:"id" json:"id"`
	StemType   string      `db:"stem_type" json:"stem_type"`
	StemData   []byte      `db:"stem_data" json:"stem_data"`
	Type       string      `db:"type" json:"type"`
	AnswerData []byte      `db:"answer_data" json:"answer_data"`
	Tags       []string    `db:"tags" json:"tags"`
}

func (q *Queries) UpdateQuestion(ctx context.Context, arg UpdateQuestionParams) (Question, error) {
	row := q.db.QueryRow(ctx, updateQuestion,
		arg.ID,
		arg.StemType,
		arg.StemData,
		arg.Type,
		arg.AnswerData,
		arg.Tags,
	)
	var i Question
	err := row.Scan(
		&i.ID,
		&i.SubjectID,
		&i.StemType,
		&i.StemData,
		&i.Type,
		&i.AnswerData,
		&i.Tags,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}
