// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users_auth.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createLoginAttempt = `-- name: CreateLoginAttempt :one

INSERT INTO login_attempts (username, ip, password_fingerprint, success)
VALUES ($1, $2, $3, $4)
RETURNING id, username, ip, password_fingerprint, attempted_at, success
`

// ───────────────────────── Login Attempts ─────────────────────────
func (q *Queries) CreateLoginAttempt(ctx context.Context, username string, ip string, passwordFingerprint *string, success bool) (LoginAttempt, error) {
	row := q.db.QueryRow(ctx, createLoginAttempt,
		username,
		ip,
		passwordFingerprint,
		success,
	)
	var i LoginAttempt
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Ip,
		&i.PasswordFingerprint,
		&i.AttemptedAt,
		&i.Success,
	)
	return i, err
}

const createPasskey = `-- name: CreatePasskey :one

INSERT INTO passkeys (user_id, credential_id, public_key, sign_count)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, credential_id, public_key, sign_count, created_at
`

// ───────────────────────── Passkeys ─────────────────────────
func (q *Queries) CreatePasskey(ctx context.Context, userID pgtype.UUID, credentialID []byte, publicKey []byte, signCount int64) (Passkey, error) {
	row := q.db.QueryRow(ctx, createPasskey,
		userID,
		credentialID,
		publicKey,
		signCount,
	)
	var i Passkey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CredentialID,
		&i.PublicKey,
		&i.SignCount,
		&i.CreatedAt,
	)
	return i, err
}

const createSession = `-- name: CreateSession :one

INSERT INTO sessions (user_id, token_hash, expires_at)
VALUES ($1, $2, $3)
RETURNING id, user_id, token_hash, expires_at, last_seen_at, created_at
`

// ───────────────────────── Sessions ─────────────────────────
func (q *Queries) CreateSession(ctx context.Context, userID pgtype.UUID, tokenHash string, expiresAt pgtype.Timestamptz) (Session, error) {
	row := q.db.QueryRow(ctx, createSession, userID, tokenHash, expiresAt)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.LastSeenAt,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, email, password_hash, role)
VALUES ($1, $2, $3, $4)
RETURNING id, username, email, password_hash, role, created_at
`

func (q *Queries) CreateUser(ctx context.Context, username string, email string, passwordHash string, role string) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		username,
		email,
		passwordHash,
		role,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions WHERE expires_at < NOW()
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredSessions)
	return err
}

const deleteLoginRateLimit = `-- name: DeleteLoginRateLimit :exec
DELETE FROM login_rate_limits WHERE scope_type = $1 AND scope_key = $2
`

func (q *Queries) DeleteLoginRateLimit(ctx context.Context, scopeType string, scopeKey string) error {
	_, err := q.db.Exec(ctx, deleteLoginRateLimit, scopeType, scopeKey)
	return err
}

const deletePasskey = `-- name: DeletePasskey :exec
DELETE FROM passkeys WHERE id = $1
`

func (q *Queries) DeletePasskey(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deletePasskey, id)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE id = $1
`

func (q *Queries) DeleteSession(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteSession, id)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getLoginRateLimit = `-- name: GetLoginRateLimit :one

SELECT scope_type, scope_key, tokens, updated_at FROM login_rate_limits
WHERE scope_type = $1 AND scope_key = $2
`

// ───────────────────────── Login Rate Limits ─────────────────────────
func (q *Queries) GetLoginRateLimit(ctx context.Context, scopeType string, scopeKey string) (LoginRateLimit, error) {
	row := q.db.QueryRow(ctx, getLoginRateLimit, scopeType, scopeKey)
	var i LoginRateLimit
	err := row.Scan(
		&i.ScopeType,
		&i.ScopeKey,
		&i.Tokens,
		&i.UpdatedAt,
	)
	return i, err
}

const getPasskeyByCredentialID = `-- name: GetPasskeyByCredentialID :one
SELECT id, user_id, credential_id, public_key, sign_count, created_at FROM passkeys WHERE credential_id = $1
`

func (q *Queries) GetPasskeyByCredentialID(ctx context.Context, credentialID []byte) (Passkey, error) {
	row := q.db.QueryRow(ctx, getPasskeyByCredentialID, credentialID)
	var i Passkey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CredentialID,
		&i.PublicKey,
		&i.SignCount,
		&i.CreatedAt,
	)
	return i, err
}

const getSessionByTokenHash = `-- name: GetSessionByTokenHash :one
SELECT id, user_id, token_hash, expires_at, last_seen_at, created_at FROM sessions WHERE token_hash = $1
`

func (q *Queries) GetSessionByTokenHash(ctx context.Context, tokenHash string) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByTokenHash, tokenHash)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.LastSeenAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, username, email, password_hash, role, created_at FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one

SELECT id, username, email, password_hash, role, created_at FROM users WHERE id = $1
`

// ───────────────────────── Users ─────────────────────────
func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, email, password_hash, role, created_at FROM users WHERE username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const listPasskeysByUserID = `-- name: ListPasskeysByUserID :many
SELECT id, user_id, credential_id, public_key, sign_count, created_at FROM passkeys WHERE user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListPasskeysByUserID(ctx context.Context, userID pgtype.UUID) ([]Passkey, error) {
	rows, err := q.db.Query(ctx, listPasskeysByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Passkey{}
	for rows.Next() {
		var i Passkey
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CredentialID,
			&i.PublicKey,
			&i.SignCount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentLoginAttemptsByIP = `-- name: ListRecentLoginAttemptsByIP :many
SELECT id, username, ip, password_fingerprint, attempted_at, success FROM login_attempts
WHERE ip = $1
  AND attempted_at > NOW() - INTERVAL '1 hour'
ORDER BY attempted_at DESC
`

func (q *Queries) ListRecentLoginAttemptsByIP(ctx context.Context, ip string) ([]LoginAttempt, error) {
	rows, err := q.db.Query(ctx, listRecentLoginAttemptsByIP, ip)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LoginAttempt{}
	for rows.Next() {
		var i LoginAttempt
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Ip,
			&i.PasswordFingerprint,
			&i.AttemptedAt,
			&i.Success,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentLoginAttemptsByUsername = `-- name: ListRecentLoginAttemptsByUsername :many
SELECT id, username, ip, password_fingerprint, attempted_at, success FROM login_attempts
WHERE username = $1
  AND attempted_at > NOW() - INTERVAL '1 hour'
ORDER BY attempted_at DESC
`

func (q *Queries) ListRecentLoginAttemptsByUsername(ctx context.Context, username string) ([]LoginAttempt, error) {
	rows, err := q.db.Query(ctx, listRecentLoginAttemptsByUsername, username)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LoginAttempt{}
	for rows.Next() {
		var i LoginAttempt
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Ip,
			&i.PasswordFingerprint,
			&i.AttemptedAt,
			&i.Success,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, username, email, password_hash, role, created_at FROM users ORDER BY created_at DESC
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.PasswordHash,
			&i.Role,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePasskeySignCount = `-- name: UpdatePasskeySignCount :one
UPDATE passkeys SET sign_count = $2 WHERE id = $1 RETURNING id, user_id, credential_id, public_key, sign_count, created_at
`

func (q *Queries) UpdatePasskeySignCount(ctx context.Context, iD pgtype.UUID, signCount int64) (Passkey, error) {
	row := q.db.QueryRow(ctx, updatePasskeySignCount, iD, signCount)
	var i Passkey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CredentialID,
		&i.PublicKey,
		&i.SignCount,
		&i.CreatedAt,
	)
	return i, err
}

const updateSessionLastSeen = `-- name: UpdateSessionLastSeen :exec
UPDATE sessions SET last_seen_at = NOW() WHERE id = $1
`

func (q *Queries) UpdateSessionLastSeen(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, updateSessionLastSeen, id)
	return err
}

const updateUserPasswordHash = `-- name: UpdateUserPasswordHash :one
UPDATE users SET password_hash = $2 WHERE id = $1 RETURNING id, username, email, password_hash, role, created_at
`

func (q *Queries) UpdateUserPasswordHash(ctx context.Context, iD pgtype.UUID, passwordHash string) (User, error) {
	row := q.db.QueryRow(ctx, updateUserPasswordHash, iD, passwordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const updateUserRole = `-- name: UpdateUserRole :one
UPDATE users SET role = $2 WHERE id = $1 RETURNING id, username, email, password_hash, role, created_at
`

func (q *Queries) UpdateUserRole(ctx context.Context, iD pgtype.UUID, role string) (User, error) {
	row := q.db.QueryRow(ctx, updateUserRole, iD, role)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const upsertLoginRateLimit = `-- name: UpsertLoginRateLimit :one
INSERT INTO login_rate_limits (scope_type, scope_key, tokens, updated_at)
VALUES ($1, $2, $3, NOW())
ON CONFLICT (scope_type, scope_key) DO UPDATE
    SET tokens = $3, updated_at = NOW()
RETURNING scope_type, scope_key, tokens, updated_at
`

func (q *Queries) UpsertLoginRateLimit(ctx context.Context, scopeType string, scopeKey string, tokens int32) (LoginRateLimit, error) {
	row := q.db.QueryRow(ctx, upsertLoginRateLimit, scopeType, scopeKey, tokens)
	var i LoginRateLimit
	err := row.Scan(
		&i.ScopeType,
		&i.ScopeKey,
		&i.Tokens,
		&i.UpdatedAt,
	)
	return i, err
}
